include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    must_be_immutable: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.i18n.dart"
    - "**/*.i18n_en.dart"
    - "**/*.i18n_es.dart"
    - "**/*.i18n_fr.dart"
    - "**/*.i18n_it.dart"
    - "**/*.i18n_ja.dart"
    - "**/*.i18n_ko.dart"
    - "**/*.i18n_pt.dart"
    - "**/*.i18n_ru.dart"
    - "**/*.i18n_zh.dart"
    - "**/*.i18n_zh_Hans.dart"
    - "**/*.i18n_zh_Hant.dart"
    - "**/*.i18n_zh_Hant"

linter:
  rules:
    avoid_print: false
    unnecessary_await_in_return: true
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    unnecessary_const: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    no_logic_in_create_state: true
    avoid_returning_null_for_void: true
    prefer_relative_imports: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_spread_collections: true
    prefer_const_constructors: true
    unnecessary_to_list_in_spreads: true
